### ISSUE TITLE
notifying users who have an existing artsy account, also add forgot password link

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eidolon#241]
![image](https://cloud.githubusercontent.com/assets/6482926/4771115/949fa3d8-5b8b-11e4-96c1-972d3c73b82f.png)

**Comment by ashfurrow** [comment]
This was added in https://github.com/artsy/eidolon/commit/1b5589c8328c7216fd106c57e2799035c5ffd263#diff-6ea32c58d4708d76b549919ed9cb681b
