### ISSUE TITLE
Registration failed generic message

### ISSUE THREAD

**Issue by dblock** [artsy/eidolon#298]
Seen several registration failed errors without an explanation. 

The bidders were actually registered, but their credit card wasn't added. This is probably a viable scenario given our general rate of cc failures, and given that it's possible users just enter bad credit cards, so maybe the registration should just succeed in this case and tell you that adding the cc has failed. When you bid, we will ask you for your cc again when that's the case.

**Comment by ashfurrow** [comment]
We can ignore failures for CC registration while the use is signing up through the "Register" button flow. It's going to be tricky for actually placing a bid, though. I think what would probably be best would be a more specific error message asking the user to talk to an Artsy rep. Does that make sense?

**Comment by ashfurrow** [comment]
Any thoughts on this @dblock ? @katarinabatina ?

**Comment by katarinabatina** [comment]
We shouldn't complete a registration if the card read is bad/fails. One first card read error, we should prompt the user to swipe again, on the second we should prompt the user to add their details manually, and if that doesnt work then we ask them to speak with an artsy rep. (in both cases of registering or placing a bid)

**Comment by ashfurrow** [comment]
Tracking in Trello: https://trello.com/c/LyhcOr1f/19-kisoks-registration-failed-generic-message
