### ISSUE TITLE
Generic can't place a bid error without an explanation

### ISSUE THREAD

**Issue by dblock** [artsy/eidolon#299]
Users were getting a generic "can't place bid" error without any explanation.

This happened to a user who had a higher position already in the system. They were the highest bidder at $1900 with a max bid of $2000. Then they already placed another higher position at $2500, but got confused thinking they were being outbid and tried to place another $2200 bid. 

In the case where you're the highest bidder we should probably ask to confirm whether you want to up the bid. And handle the case where you're trying to place a smaller bid than your own max bid better - it should say that you already have a higher max bid in the system at XYZ$.

**Comment by ashfurrow** [comment]
We've seen this – captured in a Trello card: https://trello.com/c/3yYMqBRo/31-kiosk-a-handful-of-generic-messages-for-failure-bugs-improve-network-failure-messaging It has been fixed.
