### ISSUE TITLE
Add "Send me my details" to Help Shelf

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eidolon#357]
I think this will be the "path to least resistance" to get people their credentials 

access the help button, tap "Send me my Details" enter email and send off details to email. If email is not found, surface appropriate dialogue 

![image](https://cloud.githubusercontent.com/assets/6482926/5747972/2fd122dc-9c0a-11e4-8c20-c76112f57d36.png)

![image](https://cloud.githubusercontent.com/assets/6482926/5747977/36fca0fe-9c0a-11e4-9f15-f5be9c93e1d3.png)

![image](https://cloud.githubusercontent.com/assets/6482926/5747985/4058fe68-9c0a-11e4-80ce-0f79c90a0fb6.png)

![image](https://cloud.githubusercontent.com/assets/6482926/5747990/51b57bb4-9c0a-11e4-94b4-e3fb27e2f020.png)

**Comment by ashfurrow** [comment]
Reopening because I overzealously closed it via a commit message.
