### ISSUE TITLE
Buyer's Premium

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eidolon#360]
Waiting on API to be updated and some designs from @katarinabatina.

**Comment by katarinabatina** [comment]
On artwork view, under bid button: Garamond size 32, color dark gray (#666666), link leads to modal containing additional information, still being designed 
![image](https://cloud.githubusercontent.com/assets/6482926/5982941/7be785a6-a896-11e4-925c-7039929574c4.png)

**Comment by katarinabatina** [comment]
On first page of bid preview:
![image](https://cloud.githubusercontent.com/assets/6482926/5983006/1d06ae9e-a897-11e4-806b-59a26571848d.png)
