### ISSUE TITLE
Add lot numbers to grid view and artwork view

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eidolon#362]
in grid view: avant garde 24px
http://cl.ly/image/472o3H0d3N3r
![image](https://cloud.githubusercontent.com/assets/6482926/5982873/ecb919b2-a895-11e4-8cfe-bd06292fe650.png)

in list view: avant garde 24px
![image](https://cloud.githubusercontent.com/assets/6482926/5982900/25382de6-a896-11e4-90c3-26b2ba9f28b6.png)

on artwork view: avant garde 24px
![image](https://cloud.githubusercontent.com/assets/6482926/5982924/5bb79398-a896-11e4-833c-51515958b30e.png)

**Comment by ashfurrow** [comment]
Looks sharp. Do you want this in for the next release?

**Comment by katarinabatina** [comment]
thanks! yes this will be necessary for this release, also realized it needs to be on the artwork preview on the bid screen 

![image](https://cloud.githubusercontent.com/assets/6482926/5982990/f41f34a6-a896-11e4-80d8-d261b6138f4b.png)

**Comment by ashfurrow** [comment]
Sounds good.
