### ISSUE TITLE
Many labels have incorrect font

### ISSUE THREAD

**Issue by orta** [artsy/eidolon#364]
Looked like helvetica to me on the most recent deploy.

**Comment by katarinabatina** [comment]
still true on the clock 
![image](https://cloud.githubusercontent.com/assets/6482926/6117309/87f4a8f4-b081-11e4-8335-4fe73934c6cd.png)

**Comment by ashfurrow** [comment]
Probably because those labels have fonts defined in IB and not code, and the font files are no longer in the main app's bundle. Fix should be easy.

**Comment by ashfurrow** [comment]
There are a few more of these than we first thought – I'm going to go through the storyboards and do an audit.
