### ISSUE TITLE
Improve wording around Max Bids

### ISSUE THREAD

**Issue by orta** [artsy/eidolon#365]
From Adam:

>  You are currently the highest bidder for this lot with a bid at $14,000
> 
> However, if you also have an outstanding MAX BID in the system, it does not tell you that, which may be disorienting. Let's consider updating this notice feature so that IF the high bidder has an outstanding MAX BID in the system, the bidding screen tells them e.g.:
> 
> You are currently the highest bidder for this lot with a bid at $14,000 (your max bid is $XX,XXX).

**Comment by orta** [comment]
Think this makes sense :+1:

**Comment by alloy** [comment]
Not sure if that copy is to be used verbatim, but I think the part between the parentheses (which I’m guessing is what the copy change is supposed to clarify?) could use some more explicit explanation. E.g.

> You are currently the highest bidder for this lot with a bid at $14,000. If you are outbid, your bid will be raised until $XX,XXX is reached.

Or if the text needs to be shorter, something like:

> You are the highest bidder, with a bid at $14,000. If you are outbid, your bid will be raised until $XX,XXX is reached.

This way the intent of the MAX BID will always be clear and leave room for angst in the heat of the moment.

**Comment by ashfurrow** [comment]
@katarinabatina Thoughts on this? Want me to touch base with Adam?

**Comment by ashfurrow** [comment]
@katarinabatina Any update on this?

**Comment by katarinabatina** [comment]
totally missed this, it is related to a story in force correct? https://github.com/artsy/force/issues/2476

**Comment by ashfurrow** [comment]
@katarinabatina Looks related, yeah.

**Comment by katarinabatina** [comment]
let me have a think on it, it'll have to be handled differently in the kiosk

**Comment by katarinabatina** [comment]
it will have to occur somewhere in this flow since we dont know who the user is when they initially set a bid 
![image](https://cloud.githubusercontent.com/assets/6482926/7144017/ad1462f8-e2b0-11e4-9002-da342b8bb84e.png)

**Comment by katarinabatina** [comment]
It's not an obvious problem to fix in the context of the kiosk. It seems like a really extreme edge case that I don't think we need to address at the moment.

**Comment by ashfurrow** [comment]
Since we agreed this wasn't a problem that needed immediate addressing two years ago, and it hasn't been raised since, I'm going to close. Anyone: feel free to re-open at any time.
