### ISSUE TITLE
No bidder number/pin shown after placing a bid under reserve

### ISSUE THREAD

**Issue by alessandra-castillo** [artsy/eidolon#369]
Number/pin screen does not should show up, you see the screen that says "Higher Bid Needed" with buttons that say "Place Higher Bid" or "Continue". 

When you go to "Place Higher Bid", you can place it without entering bidder number and pin, but still never get to that page with bidder number/pin.

**Comment by ashfurrow** [comment]
We only show bidder number and pin if the user was newly created. Is it possible that you were testing with an existing user?

**Comment by ashfurrow** [comment]
Wait, the PAF auction doesn't have reserves, does it? Gonna move this back to the 4.0 milestone.

**Comment by alessandra-castillo** [comment]
Correct, PAF does not have starting bids :)

On Fri, Apr 10, 2015 at 3:36 PM, Ash Furrow <notifications@github.com>
wrote:

> Wait, the PAF auction doesn't have reserves, does it? Gonna move this back
> to the 4.0 milestone.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artsy/eidolon/issues/369#issuecomment-91661086>.
>



-- 
[A.]        Alessandra Castillo / Curatorial Liaison
               Artsy <http://artsy.net> / 401 Broadway, 25th Floor, New
York, NY 10013

               alessandra@artsy.net
               +1 401 601 6555

               Artsy for Museums
<https://www.artsy.net/pdf/institutions-overview.pdf> | Auctions
<https://www.dropbox.com/s/mmvvbprnbf0eyio/ArtsyAuctions.pdf>

**Comment by ashfurrow** [comment]
Fixed!
