### ISSUE TITLE
Adding a "Confirm" or "Close" button to the highest bid screen

### ISSUE THREAD

**Issue by alessandra-castillo** [artsy/eidolon#373]
To exit screen you have to click "Cancel" in the upper left-hand corner. You can't click out by tapping outside the screen. Makes bidders think they're canceling their high bid. 

![img_0014](https://cloud.githubusercontent.com/assets/9465284/6189972/ba7b862e-b36c-11e4-978f-68757bfcebe4.PNG)

**Comment by ashfurrow** [comment]
Huh – missed that typo until now:

> You are are the ...

**Comment by ashfurrow** [comment]
The `TODO` right above it makes it even better :)

https://github.com/artsy/eidolon/blob/0077f8f7457eb57625fb4aefbafad0885cb3b65f/Kiosk/Bid%20Fulfillment/LoadingViewController.swift#L153-L154
