### ISSUE TITLE
No prompt for Pin after entering Bidder Number

### ISSUE THREAD

**Issue by alessandra-castillo** [artsy/eidolon#374]
After entering a bid and your bidder number, you're prompted to enter an email address >> Artsy password >> then bid is placed. Instead, it should be prompting you to enter your pin.

BUT If you enter your phone number instead of bidder number, it correctly prompts you to enter your pin.

**Comment by alessandra-castillo** [comment]
**UPDATE** 
This issue happens AFTER you register, so our system already has cc info. Here are the user workflows post-registration.  

**Using Bidder Details**
Place bid >> Enter Bidder Number >> Enter Pin >> asked to swipe cc again (header at top of page says "Register to Bid") >> Confirm information (header at top of page says "Register to Bid")>> Bid is placed.

**Using Artsy Details** 
Place bid >> Opt to enter Artsy email/password >> asked to swipe cc again (header at top of page says "Register to Bid") >> Confirm information (header at top of page says "Register to Bid")>> Bid is placed. 

**Enter Phone Number**
Place bid >> Enter Phone Number >> Enter Pin >> asked to swipe cc again (header at top of page says "Register to Bid") >> Confirm information (header at top of page says "Register to Bid")>> Bid is placed.

@katarinabatina can you confirm that this design is intentional? would love to clean this up before kiosk dev gets put on hold. cc: @ashfurrow

**Comment by katarinabatina** [comment]
@alessandra-castillo the nature of the flows which you are describing are somewhat by design but there is an obvious bug here

**Comment by ashfurrow** [comment]
Seems very similar to #419.

**Comment by ashfurrow** [comment]
OK, so this is fixed!
