### ISSUE TITLE
Add "Forgot Password" link when going through the Register to Bid workflow

### ISSUE THREAD

**Issue by alessandra-castillo** [artsy/eidolon#376]
When you click the "Register to Bid" button and our system recognizes an email address of an Artsy user, you get a screen without a "Forgot Password" link. 
![img_0032](https://cloud.githubusercontent.com/assets/9465284/6220522/5ad32f2e-b605-11e4-8022-5339553c7087.PNG)
I'd love for it to look like the image below. You get the "Forgot Password" link by clicking "Bid" and going through that workflow. 
![img_0034](https://cloud.githubusercontent.com/assets/9465284/6220661/10251364-b607-11e4-92a1-a2db5d8d09f0.PNG)

**Comment by katarinabatina** [comment]
Felt like once upon a time it used to be there???

**Comment by alessandra-castillo** [comment]
@katarinabatina it definitely appears if you place a bid, enter an amount, and opt to "Use Artsy Login Details". But not under the "Register to Bid" workflow.

**Comment by katarinabatina** [comment]
right, looking at the original design I specked though it should look closer to 
![image](https://cloud.githubusercontent.com/assets/6482926/7075835/f4050b54-ded2-11e4-8b92-38636ec0a765.png)

**Comment by katarinabatina** [comment]
ignore the yellow information to the right

**Comment by katarinabatina** [comment]
Right, I guess as originally designed it should look like this on that step 
![image](https://cloud.githubusercontent.com/assets/6482926/7075879/537092f2-ded3-11e4-8c36-e124fa32da2f.png)
