### ISSUE TITLE
Make the entire row clickable in grid views

### ISSUE THREAD

**Issue by dblock** [artsy/eidolon#391]
I witnessed a user at LAMA desperately tap on the line for a lot in the grid view (the A-Z view I think) until (after no less than 10 tries and almost giving up) they finally saw the bid button and clicked on that. I think Bid should lead you to an actual bid page while tapping on the work or anywhere else on the line should lead you to more focused info.

**Comment by dblock** [comment]
cc: @katarinabatina

**Comment by katarinabatina** [comment]
@ashfurrow I think increasing the tap area per list item unit is worth while, we will want to make sure it doesn't make for an annoying scroll experience (increase likelihood of miss-taps).

**Comment by ashfurrow** [comment]
Yup. This was captured in #312 but never gotten to. I'll prioritize it and close the other issue.
