### ISSUE TITLE
Feature request: overview of multiple sales

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eidolon#399]
In talking with the auctions team last week it sounds like there won't be any major feature requests that are kiosk specific in the coming months. The one possible request there might be is an overview of multiple sales. This would serve the purpose for commercial auctions, in which kiosks would be on display at an auction house during previews of various sales and would be used to browse the lots. A rough sketch below 

![image](https://cloud.githubusercontent.com/assets/6482926/6791039/69e8fe74-d182-11e4-9c3c-8694e65ba1ce.png)

It is unclear at the moment where kiosks fit into the commercial auction user experience but it's clear that it probably won't play an integral role in the actual bidding process. Seeing as this is only a preliminary idea I though it would be best if you could comment on the amount of work you think there would be to develop this type of page.

**Comment by ashfurrow** [comment]
We would need the web team to develop a "related auctions" endpoint or relationship for us, as well as the ability to specify images for those auctions. Is there any interaction involved? Can users tap on these auctions? If so, what happens?

**Comment by katarinabatina** [comment]
Yes they would be able to tap on the auctions and land on the grid view of works, browse the works. There may be a potential to not allow bidding on the works but kind of unclear

**Comment by ashfurrow** [comment]
Hmm. Our app makes the assumption – from the point when the app is launched to the point it is closed – that it is only displaying lots from one auction. Abstracting this out to be variable within the application's lifecycle would require a lot of testing for me to be comfortable with it. 

It sounds almost like this is another app? A sort of "Auction House" kiosk – instead of an "auction event" kiosk. Would it make sense to build a separate app?

**Comment by katarinabatina** [comment]
If it meant that the scope would actually be smaller I think that would make sense. The likelihood of a major auction house allowing someone to bid without going through a thorough vetting process is small.

**Comment by ashfurrow** [comment]
Cool! Abstracting the existing parts of eidolon out to be reusable components that another app could use sounds

- Awesome
- Practical
- Fun

So I'm :+1:

**Comment by katarinabatina** [comment]
That was so poetic. Probably hard to guess given lack of detail right now but if you were to TRY, how long do you think an app like this would take?

**Comment by ashfurrow** [comment]
Cool – why don't we chat IRL?
