### ISSUE TITLE
Urgent: Kiosk is not pulling the first (primary) image for each lot. 

### ISSUE THREAD

**Issue by alessandra-castillo** [artsy/eidolon#401]
Each lot has a primary image, which shows up as the main image for the auction lot (primary images seen here - artsy.net/algorithm-auction). The kiosk is selecting additional detail images for each lot. 

For Chris Coyne's lot, the primary image should be:
![screen shot 2015-03-26 at 4 37 20 pm](https://cloud.githubusercontent.com/assets/9465284/6856439/7e262a32-d3d6-11e4-92d1-7837c421a4ed.png)

But the kiosk is pulling: 
![chris_coyne_lot](https://cloud.githubusercontent.com/assets/9465284/6856451/8a831dc6-d3d6-11e4-802b-2a6368482ddc.jpg)

**Comment by alessandra-castillo** [comment]
FYI: the Auctions App is also pulling the wrong image. 

https://auctions.artsy.net/sales/the-algorithm-auction/artworks

**Comment by ashfurrow** [comment]
Looks like there's a (possibly new?) `is_default` flag. Adding it now.

**Comment by dblock** [comment]
This was fixed, closing.
