### ISSUE TITLE
"No estimate" text under each Algorithm Auction lot

### ISSUE THREAD

**Issue by alessandra-castillo** [artsy/eidolon#402]
"No estimate" is showing up under each auction lot. It's true that there are no estimates for this auction, but it would be appreciated if that text didn't appear. 
![img_0471](https://cloud.githubusercontent.com/assets/9465284/6856534/06bf4bbc-d3d7-11e4-8c43-0135db255392.jpg)

**Comment by ashfurrow** [comment]
@katarinabatina Any design input on this one?

**Comment by katarinabatina** [comment]
just omit the filed if nothing is there?

**Comment by ashfurrow** [comment]
Totally can-do.

**Comment by katarinabatina** [comment]
:+1:

**Comment by ashfurrow** [comment]
What are we going to do for #396, which looks like it has consistent cell heights?
