### ISSUE TITLE
If you try to register to bid and the account exists it tells you incorrect password

### ISSUE THREAD

**Issue by dblock** [artsy/eidolon#417]
During registration if the account already exists you see incorrect password flash. It's confusing - the reason why this happens is that the account already exists, so it should say so.

**Comment by ashfurrow** [comment]
Looks like it is actually trying to update the user, but the API call is failing. Looking into it.

**Comment by ashfurrow** [comment]
Yeah, wasn't logging in first to update user. Fixing now.
