### ISSUE TITLE
You cannot enter your phone to confirm the bid

### ISSUE THREAD

**Issue by dblock** [artsy/eidolon#418]
Doesn't let you enter more than six digits, but tells you that you should be able to.

![2015-04-09 14 33 26](https://cloud.githubusercontent.com/assets/542335/7074026/96e6ef80-dec5-11e4-8556-b1803088cd4f.jpg)

**Comment by ashfurrow** [comment]
Looks like it's caused by this line, originally designed to cap bids at a million dollars: https://github.com/artsy/eidolon/blob/0fb530799c827326d8111af977a56a61c9fe8f9f/Kiosk/Bid%20Fulfillment/KeypadViewModel.swift#L75
