### ISSUE TITLE
After Bidding by entering Bidder # and Pin #, you're prompted to swipe CC again. 

### ISSUE THREAD

**Issue by alessandra-castillo** [artsy/eidolon#419]
The bid should be placed without swiping your CC, since you already swiped it to receive a bidder number and pin. These are the screens I saw after bidding, entering Bidder #, and entering Pin #: 

1. Swipe CC Screen
![img_0002](https://cloud.githubusercontent.com/assets/9465284/7075300/dc66cf7c-dece-11e4-933e-3ef581e2f0a0.PNG)

2. Register to Bid Confirmation Screen
![img_0003](https://cloud.githubusercontent.com/assets/9465284/7075306/ed075446-dece-11e4-8cb4-6a866a1e7711.PNG)

**Comment by ashfurrow** [comment]
OK, this is actually fairly involved. There are a lot of ways to arrive here. Basically, I get the idea that once the system has a CC on file, it shouldn't even prompt you again for one, right? 

So the issue really is getting to know whether or not you have a CC on file. @alessandra-castillo I don't think we infer that if a user is registered for the auction, that they have a CC. And normally we could just ask the API if the user is registered yet, but we need to log in as the user to do that first, and we need their password to log in, first. 

I think, in combination with #374, we need to sit down with @katarinabatina and go over the flows to make sure we're on the same page, then I can identify what new server APIs we need, if any, and then we can implement this. 

I don't think this is viable for Monday's 3.4 release.

**Comment by ashfurrow** [comment]
We just tested this, and even on production (!), it works.

**Comment by ashfurrow** [comment]
It only doesn't work when testing on staging because adding credit cards on staging doesn't work, so users are always asked for CC info.

**Comment by katarinabatina** [comment]
Aha! Well done! 

Katarina
