### ISSUE TITLE
Place bid image placement

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eidolon#430]
It's lower-left and should be centred.

**Comment by katarinabatina** [comment]
what view are you referring to here, this view? 
![image](https://cloud.githubusercontent.com/assets/6482926/7190314/3d974914-e453-11e4-9aa9-ff02fd67cfa0.png)

**Comment by ashfurrow** [comment]
Yes that one.

**Comment by ashfurrow** [comment]
This is no longer happening.
