### ISSUE TITLE
eliminate interstitial screen between finishing reg. and seeing details

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eidolon#437]
![image](https://cloud.githubusercontent.com/assets/6482926/7283425/71dfc902-e904-11e4-8bc4-a260f6694390.png)

Don't know when this got added but this screen should just lead to the users bidder details

**Comment by katarinabatina** [comment]
reference http://cl.ly/0p0K2i420L1d

**Comment by ashfurrow** [comment]
Hey @katarinabatina – could I get a clarification on something? Should we skip this screen entirely (go from "Registering ..." to the "here are you deets" screen)? Or change the page from "Registering ..." to "Registration Completed", and the advance to the details screen after a delay? The reference movie has this slick animation that we don't really have time to do.

**Comment by katarinabatina** [comment]
Lets have a "registration completed" confirmation but then advance to the
following screen (without requiring the user to manually advance it a step
further)

[A.] Katarina Batina

Artsy <http://artsy.net/>


katarina@artsymail.com

                @katarinabatina <https://twitter.com/katarinabatina>

253 225 5812

**Comment by ashfurrow** [comment]
OK cool. One second sound reasonable?

**Comment by katarinabatina** [comment]
yup


[A.] Katarina Batina

Artsy <http://artsy.net/>


katarina@artsymail.com

                @katarinabatina <https://twitter.com/katarinabatina>

253 225 5812
