### ISSUE TITLE
Investigate RxSwift

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eidolon#448]
Really cool [functional reactive programming framework](https://github.com/kzaher/RxSwift) for Swift. We were going to move from RAC 2 -> RAC 3, but it might make more sense to switch to this, instead.

**Comment by sjmueller** [comment]
It would be great for the community if you could share the thoughts that led to continuing with RAC 3 instead of RXSwift.  Thanks!

**Comment by orta** [comment]
To my knowledge, so far, that's not been decided. Roughly speaking this is a pretty big app, and either choice requires significant re-writing.

**Comment by ashfurrow** [comment]
That is correct; we are still using the ReactiveCocoa 2 ObjC API, leading to a lot of forced casting. RxSwift is still too early to use, but RAC 3 is also in a constant state of flux. I'm leaning toward RxSwift, since I've been working with them on the project recently, but we've not had a chance to devote the effort to change Eidolon. 

Does that answer your question? Happy to clarify anything.

**Comment by sjmueller** [comment]
Yes, that answers my question!  This app is one of the few shining examples of a modern, well-written codebase and tech stack with swift, so thank you immensely for sharing :)
