### ISSUE TITLE
When a work is sold (via buy now) at an auction it needs to say so

### ISSUE THREAD

**Issue by dblock** [artsy/eidolon#453]
If a work at auction is bought via "buy now", it should say Sold in the UI. Right now you can still bid on it.

**Comment by dblock** [comment]
The server-side logic is that you can buy a work now as long as it hasn't met reserve, https://github.com/artsy/gravity/blob/master/app/models/domain/sale_artwork.rb#L191.

**Comment by ashfurrow** [comment]
Estimate: 0.5 days.

**Comment by ashfurrow** [comment]
Judging from [this line](https://github.com/artsy/gravity/blob/fb692948df45c793ca58904ca0cac48ab6fc5363/app/models/domain/sale_artwork.rb#L201), it looks like whether or not an artwork can be sold is an attribute on the artwork model, not the sale artwork model. 

I'd prefer to use the `sold` field of the JSON model, but that can be false if there are [other editions for sale](https://github.com/artsy/gravity/blob/fb692948df45c793ca58904ca0cac48ab6fc5363/app/models/domain/artwork.rb#L788-L790), so I'm going to use `availability` instead: "sold" is sold and anything else is not sold. @dblock please let me know if this sounds unreasonable.
