### ISSUE TITLE
When you bid on a work that has just sold you get Bid Failed

### ISSUE THREAD

**Issue by dblock** [artsy/eidolon#454]
![img_0003](https://cloud.githubusercontent.com/assets/542335/7661880/94f69aba-fb24-11e4-860c-8efc4212f35e.PNG)

A work that is already sold via buy now just displays "Bid Failed" when you try to bid on it. Really it should say the artwork has been already sold.

Generally we need an explanation next to Bid Failed which is useful. Maybe I can tap and hold the message and get details instead of a generic message because when this happens we have an irate user standing there and a powerless Artsy person.

**Comment by katarinabatina** [comment]
why are we even showing sold works? clearly the server knows they not for sale?

**Comment by dblock** [comment]
This bug is more general, bid failed is not useful and there're 10 reasons why the server may not place a bid. We need to know why because we look stupid in front of the customer with something that's not actionable. 

There's another issue about not letting you bid on works that have sold, https://github.com/artsy/eidolon/issues/453.

**Comment by ashfurrow** [comment]
I think at the very least, we should log the response from the server so that it shoes in the admin logs (accessible by Artsy staff at the event) so they can see what actually went wrong. I think having more specific user-facing error messages for common failure reasons would be great 👍

**Comment by dblock** [comment]
We very rarely examine logs in the hustle of the auction and much less later. Tracking an iPad is hard. Long term we probably want to "see" how kiosks are doing from a server-side control panel.

If we don't want to display the ugly error message, maybe we want to make it possible to hold the error message with a finger and that would expand, just an idea.

**Comment by ashfurrow** [comment]
That's a swell idea, dB.

**Comment by ashfurrow** [comment]
Estimate: 1 day.
