### ISSUE TITLE
Swallowed error on entering cc

### ISSUE THREAD

**Issue by dblock** [artsy/eidolon#455]
Witnessed a user register, enter a cc, then enter an expiration date, then hit ok and get nothing back. Spinner spinned, then the button came back clickable without any errors. CC seems to have been entered into the system. The only workaround was to take someone's bid on an ipad. Trying to bid again on a kiosk was asking for the cc again, didn't retry.

**Comment by dblock** [comment]
The user ID was 55566e42726169628ea70000

**Comment by orta** [comment]
This was when entirely manually entering the details?

**Comment by ashfurrow** [comment]
So this was using the manual CC entry screen instead of the card reader? Any indication it happened with the reader, too?

**Comment by ashfurrow** [comment]
Haha – sorry, Orta. Didn't see your comment. Shouldn't GitHub before coffee.

**Comment by alessandra-castillo** [comment]
hey @ashfurrow @orta the user registered using the card swiper (not manually entry).

**Comment by ashfurrow** [comment]
Thanks Alessandra!

**Comment by dblock** [comment]
The user registered a card swiper, but was required a cc again to confirm a bid? Now I am confused :)

**Comment by ashfurrow** [comment]
Yeah, me too. The original bug was that they entered the info manually. Just to verify, whoever saw this saw it happen with:

- [ ] manual entry
- [ ] card reader

**Comment by alessandra-castillo** [comment]
@ashfurrow To verify: in this case that dB is describing, the user entered her credit card information manually. I've replicated this bug by registering on the kiosk (on staging). After entering my credit card number and expiration date, I cannot proceed. The "Enter" button is clickable, but nothing happens. 
![img_0004](https://cloud.githubusercontent.com/assets/9465284/7753536/1b622a22-ffb4-11e4-8d0c-f8f455d31a2d.PNG)

**Comment by ashfurrow** [comment]
OK, good catch @alessandra-castillo – I'll take a look. Strange that a Kiosk was on manual entry mode anyway, but this should still be fixed. Thanks!

**Comment by alessandra-castillo** [comment]
@ashfurrow yes very strange, I can't pin down who switched it and why! Thanks for looking into it.

**Comment by ashfurrow** [comment]
Estimate: 0.5 days.

**Comment by ashfurrow** [comment]
Looks like the problem is that the `finishedSignal` is never sent a completion once the registration succeeds. This would cause the CC to be tokenized but never attached to a user record and not advance the UI to the next registration step. 

Writing a test to reproduce now, then I'll have a PR soon.
