### ISSUE TITLE
Bidders prompted to swipe CC after placing every bid

### ISSUE THREAD

**Issue by alessandra-castillo** [artsy/eidolon#459]
This is a bug we encountered before, but came up again at Choice Works. Bidders registered with me at the Kiosk, swiped their CC, and obtained a bidder number and pin. But after using that bidder number and pin, they were still asked to swipe their credit card. 

Unfortunately this is not something I can test via staging, since staging does not store credit cards and will always prompt to enter your cc. But I noticed it with at least two bidders that I personally registered at the event.

**Comment by ashfurrow** [comment]
Hmm, ok thanks Alessandra. We'll look into it.

**Comment by ashfurrow** [comment]
Estimate: 0.5 days.

**Comment by ashfurrow** [comment]
Had trouble reproducing this yesterday. Probably going to fall into the next sprint.

**Comment by ashfurrow** [comment]
OK, so this _should_ be fixed. Let's keep an eye on this. Thanks Alessandra!
