### ISSUE TITLE
CardFlight Errors

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eidolon#467]
Alessandra reported a problem with credit card tokenization. It fails on production when registering for a new account or when using the admin CC testing screen.

Reproduced from last Hockey build; unable to reproduce when installing from Xcode. No keys have changed since the last build. Going to try to distribute a new version to see if that fixes the problem.

**Comment by ashfurrow** [comment]
Alessandra and I have both confirmed that a new build submitted to Hockey fixed the problem. I'm not sure why it went wrong. My best guess is that the previous build used an older CardFlight API token. I don't know how it could've worked before, though.

**Comment by orta** [comment]
Could we leave a SHA of the token in the app somewhere and do a test against it?

**Comment by ashfurrow** [comment]
Yup – part of the unit tests? Deploy process? Any others?

**Comment by orta** [comment]
deploy probably, can compare `bundle exec pod keys get XXX` - doing it in tests won't work without giving travis/circle our real secrets

**Comment by ashfurrow** [comment]
Tests could check for the SHA comparison _or_ a known stubbed key (the app currently defaults to stubbed behaviour only for one-character keys, for example).
