### ISSUE TITLE
Fastlane deploys not working

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eidolon#468]
Unable to create archive.

```sh
▸ Running script 'Embed Pods Frameworks'
** ARCHIVE FAILED **


The following build commands failed:
	PhaseScriptExecution Embed\ Pods\ Frameworks /Users/ash/Library/Developer/Xcode/DerivedData/Kiosk-dywhoqbddoimmpfuccrbwpyyoagk/Build/Intermediates/ArchiveIntermediates/Kiosk/IntermediateBuildFilesPath/Kiosk.build/Release-iphoneos/Kiosk.build/Script-0ED47F96B607F7D4857C5E68.sh
(1 failure)
```

Works in Xcode/Hockey Mac app directly upload.

**Comment by KrauseFx** [comment]
Since you're using the `ipa` action [here](https://github.com/artsy/eidolon/blob/master/fastlane/Fastfile#L68-L74) you might want to try using `shenzhen` directly to see what's causing the error. `shenzhen` will also print out the plain `xcodebuild` command.

**Comment by ashfurrow** [comment]
Cool, thanks!

**Comment by ashfurrow** [comment]
Proceeding on #410 which will further break this. We should take this opportunity to update fastlane, too.

**Comment by ashfurrow** [comment]
Looking further into this, it appears that this was a problem with multiple certificates with the same name. The latest version of Fastlane surfaced the error message :+1:

**Comment by KrauseFx** [comment]
:+1:
