### ISSUE TITLE
Kiosk crashes after selecting "Grid View" from any other lot view

### ISSUE THREAD

**Issue by alessandra-castillo** [artsy/eidolon#473]
:(

**Comment by orta** [comment]
Which auction?

**Comment by ashfurrow** [comment]
amFar

**Comment by alessandra-castillo** [comment]
I'm not sure if this matters, but the app also crashes if you switch back to grid view in LAMA auction on Staging.

**Comment by ashfurrow** [comment]
Yup – I see the problem. The API is serving images with no aspect ratio, and our code currently expects one (and defaults to zero). Later, when we use this as the denominator of a division operation, well...
