### ISSUE TITLE
Kiosk displaying "No Estimate" when estimate field is actually filled 

### ISSUE THREAD

**Issue by alessandra-castillo** [artsy/eidolon#474]
New "Estimate" field was recently added to the Auctions App and first used in the amfAR generationCURE auction.
![screen shot 2015-06-25 at 4 31 00 pm](https://cloud.githubusercontent.com/assets/9465284/8364951/e476440c-1b57-11e5-895e-f7b019e58225.png)

My guess is that the kiosk doesn't know to pull estimates from that new field, and instead displays "No Estimate." 
![img_0004 2](https://cloud.githubusercontent.com/assets/9465284/8364987/31ceac3a-1b58-11e5-9de5-105b125d8dbf.PNG)

**Comment by ashfurrow** [comment]
Yup, I think your guess is right.

**Comment by ashfurrow** [comment]
So what we're going to do is default to showing the new estimate field. If one's not provided, then we'll show the range. If there is neither, we'll display "No Estimate" – sound good?
