### ISSUE TITLE
build this sprint

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eidolon#481]
This sprint will take us to the beginning of the auction season. Not sure what our first auction date is do you? It would be good to add issues to this sprint based on the must haves for the opening of auction season. Alloy will also be away next sprint so ideally we'd want you 30/70 eidolon/eigen if possible

**Comment by ashfurrow** [comment]
Yeah, I've not heard anything specific. Last I checked it was sometime in September. I'll check with Alessandra.

**Comment by katarinabatina** [comment]
@ashfurrow closing this issue, iv'e built most this sprint in the milestone

**Comment by ashfurrow** [comment]
Cool – I've added a small bug, a crasher, and a deployment problem to [the milestone](https://github.com/artsy/eidolon/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22July+21+-+Aug+25%22).
