### ISSUE TITLE
Request a $1 hold on a user's credit card

### ISSUE THREAD

**Issue by orta** [artsy/eidolon#483]
Full context: https://github.com/artsy/force/issues/3146

> Right now you can use any credit card number provided at http://www.getcreditcardnumbers.com with garbage information in your billing address.

**Comment by ashfurrow** [comment]
Hmm interesting. Let's see how the force issue shakes out.

**Comment by ashfurrow** [comment]
We've addressed this through collection of zip code and CVV.
