### ISSUE TITLE
Dynamic frameworks load time?

### ISSUE THREAD

**Issue by marcelofabri** [artsy/eidolon#491]
I'm seeing large load times when using dynamic frameworks on my app and decided to check if this was an issue for you guys too.

I could reproduce the issue on an iPad 3 here and sometimes the app won't even launch due to the WatchDog. Am I missing something here? Do you really suffer from this issue too?

This seems to be the same issue as https://github.com/artsy/eigen/issues/586.

**Comment by orta** [comment]
Are you on iOS9?

**Comment by marcelofabri** [comment]
iOS 8.1

**Comment by orta** [comment]
We definitely saw a longer launch time for eigen, it was significant on iOS 9 devices ( after being compiled and deployed from Xcode 6 ) but it wasn't worrying on  eigen ( which has way more Pods ) for the last release.

**Comment by ashfurrow** [comment]
I've seen long launch times, but nothing that would stop the app from launching. Maybe the hardware we run on is fast enough. Iit hasn't been a pressing issue for us on this app since it's an internal tool.

**Comment by marcelofabri** [comment]
> Aug  3 17:05:29 iPad-3-iOS-81 ReportCrash[495] <Error>: net.artsy.kiosk.beta failed to launch in time
> Aug  3 17:05:29 iPad-3-iOS-81 ReportCrash[495] <Error>: Elapsed total CPU time (seconds): 22.320 (user 22.320, system 0.000), 55% CPU 

I'm wondering how aren't there more people talking about this problem on their apps.

I mean, we're almost dropping dynamic frameworks because of this. I also opened a DTS with Apple to see if there's any official word on this.

**Comment by ashfurrow** [comment]
I think @alloy did some [testing on eigen](https://github.com/artsy/eigen/issues/586) and the problem primarily affects debug builds. There's also a helpful command there to shorten the time.

**Comment by marcelofabri** [comment]
Yeah, I checked that, but I'm also seeing the issue on release builds. Also, if I understood correctly, that command will statically link all frameworks and (I think) Swift frameworks need to be dynamically linked.

**Comment by brianmichel** [comment]
I've been seeing this recently in our app as well, doing some more investigating and lead me here. You are not alone :)

**Comment by orta** [comment]
I don't think we have either: Asked on the Apple Dev Forums, or done a DTS support ticket. Both would expand the surface area of people who might be in the know about ways around it. 

Other ideas, @neonacho pointed me at https://github.com/johnno1962/Accelerator last night

**Comment by marcelofabri** [comment]
Here was our DTS response: 

> Thank you for contacting Apple Developer Technical Support (DTS).
>
> I discovered that these long load times only happen when the debugger is attached. If you select Product > Profile and look at the console in Instruments instead, you will notice the time is in milliseconds instead of seconds.
>
>dyld reports a higher time when the debugger is attached because the debugger halts execution after each framework is loaded in order to gather information. That time that the process is halted counts against the dyld load time because dyld uses mach_absolute_time() to record the time at the start and end of loading frameworks and then prints the difference.
>
>If you are seeing poor framework loading performance without a debugger attached, please file a bug so our dyld engineers can take a look. Combining frameworks may reduce the loading time, but you will hit a lower bound of frameworks since you can’t combine the Swift frameworks bundled with your app.

However, our app still takes 8s to load (7.4s on "total images loading time"). I just responded to the DTS and I'm waiting for a response. On the meantime, I'll test https://github.com/johnno1962/Accelerator.

**Comment by alloy** [comment]
@marcelofabri Yeah that’s basically the same as reported on the Eigen thread. In our case startup is a bit slower the first time you launch the app, thereafter it goes smoother.

**Comment by alloy** [comment]
@marcelofabri Keep us posted of your communication please! :heart:

**Comment by marcelofabri** [comment]
Here's what I was able to measure on our project about `total images loading time`:

| | First Time | Second Time
-------|------------ | -------------
**Dynamic frameworks** | 7.3 seconds (91.0%) |66.74 milliseconds (9.5%)
**Accelerator** | 7.7 seconds (90.6%) | 43.50 milliseconds (7.8%)

**Comment by johnno1962** [comment]
Bother.. In the finish I only see the slowdown on frameworks in the debugger too. Well, at least this is one approach we can eliminate!

**Comment by alloy** [comment]
@johnno1962 I love your try it and eliminate hands-on approach, thanks for your efforts and input! :heart:

**Comment by orta** [comment]
This eventually came to a conclusion in 9.3 - see the eigen issue for full details
