### ISSUE TITLE
Where do you keep the *real* keys?

### ISSUE THREAD

**Issue by marcelofabri** [artsy/eidolon#493]
I've seen that dummy keys are setup up with `fastlane`. Is that where do you keep the *real* keys too?

Thanks!

**Comment by ashfurrow** [comment]
Hi! Good question. Keys are stored in the OS X Keychain, using this CocoaPods plugin: https://github.com/orta/cocoapods-keys

**Comment by marcelofabri** [comment]
Yeah, but how do you keep them in sync? E.g. someone joins Artsy today, how does she add the keys using cocoapods-keys?

**Comment by orta** [comment]
and if you're interested in how the team keeps the keys together, we use 1password with the output of `bundle exec pod keys` then when doing a `bundle exec pod install` we c&p them over.

**Comment by orta** [comment]
yeah, ^ that is how they do it. I've debated making the thing in 1password a collection of `bundle exec pod keys set XXXKey XXXValue` instead, but the output from keys is reasonable enough.

**Comment by marcelofabri** [comment]
:+1: 

I didn't even know that 1Password supported shared vaults. Cool!

**Comment by ashfurrow** [comment]
Yeah, it's a good system for a team our size. The nice thing is that CocoaPods-Keys should scale well, in a team where individual developers might have different keys, and a build server might have the deploy keys, or something.
