### ISSUE TITLE
Card errors are unrecoverable

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eidolon#497]
Our `CardHandler.swift` currently sends errors on Card Flight errors, which is fine, but our `SwipeCreditCardViewController` handles errors by telling users something went wrong. The problem is that once a CC swipe errors, the signal no longer sends values, and subsequent card swipes aren't recognized at all. You would need to re-instantiate the view controller to get it working again. Confusing UX.

**Comment by devangt** [comment]
@ashfurrow do you think the results of this could manifest itself as the feedback we saw in a few auctions captured here: https://trello.com/c/wzzK232J/22-kiosk-cc-credential-management

**Comment by ashfurrow** [comment]
Definitely possible – I was still a bit unclear about how that bug presented itself. 

This problem would be:

1. User is asked to swipe their card.
1. The tokenization fails for whatever reason (swiped too quick/slow, api is down, network hiccup, etc).
1. The user sees an error, and is asked to swipe again, but the card reader is no longer listening for swipes.

**Comment by ashfurrow** [comment]
Obviated.
