### ISSUE TITLE
Update RFP parts to RAC 3.0

### ISSUE THREAD

**Issue by skyylex** [artsy/eidolon#525]
I've noticed that application is built upon the ReactiveCocoa 2.0 core concepts, I mean RACSignal and RACComands. 

Does it make sense to update them to the "more Swifty" RAC 3.0 Signal/SignalProducer/Action abstractions?

**Comment by ashfurrow** [comment]
Hey! That's correct – we began building this application before RAC 3 had even reached an alpha! 

ReactiveCocoa 3 supports Swift 1.2 only, and the 4.0 release for Swift 2 is still in alpha. We're planning on making the switch within the next few months. Maybe to ReactiveCocoa 4, maybe to [RxSwift](https://github.com/ReactiveX/RxSwift). When we do, I'll reference this issue on the pull request – if you have any feedback, we'd love to hear it!

**Comment by skyylex** [comment]
Thx for quick response, @ashfurrow. I see your point. Could I help with anything?

Also I'm very appreciate this open-sourced application that demonstrates the concepts of RFP in iOS. There are not to much real-world practices in Swift related to RFP.

**Comment by ashfurrow** [comment]
Hey, thanks @skyylex – it's ok, it' gonna be a big project :) 

Happy to open our source code :cake:

**Comment by ikovalisko** [comment]
@ashfurrow Could you please share you concerns about upgrading to RAC 4.0? Why moving to RxSwift?

After almost 2 years using RAC 3, I found myself learning version 4 concepts from scratch. They don't look simpler and routine tasks have to be solved in rather different way. Maybe it's Swift style + new names for old things. 
At the moment I'm hesitating to switch to RXSwift  or continue with RAC 4.0.

**Comment by orta** [comment]
Most of our discussion around RAC was summed up in [this blog post](http://artsy.github.io/blog/2015/09/18/Cocoa-Architecture-Dependencies/)

**Comment by ashfurrow** [comment]
Yeah, we're not sure what we're going to do. I can't really comment on the motivations for the changes to RAC 4. Right now, we're leaning towards RxSwift at the moment, just to try something new. Additionally, RxSwift adheres to the common APIs at [ReactiveX.io](http://ReactiveX.io), so the domain knowledge is transferrable to other platforms, and also very stable and predictable.

**Comment by ashfurrow** [comment]
Hey there! Just following up on this. This week, we [completed our transition to RxSwift](https://github.com/artsy/eidolon/pull/569). I wrote up a [summary of the process on Artsy's blog](http://artsy.github.io/blog/2015/12/08/reactive-cocoa-to-rxswift/). Let me know if I can clarify anything!
