### ISSUE TITLE
using 1Password

### ISSUE THREAD

**Issue by jsleeuw** [artsy/eidolon#567]
Wondering if you might be able to provide a few details on how you're using 1Password. The cocoapods-keys plugin looks really interesting. Have you found a way to keep tokens and passwords hidden from developers, or are they visible, but just kept in a 1Password vault? Are you guys using 1Password for teams? 

Thanks for any info that you can share!

**Comment by orta** [comment]
Our tokens are known to developers, given that the company is still pretty small this is no problem. We currently share a 1password file on dropbox with ~25 devs in Artsy. It's a hassle once every few months with conflicts, but it's been worth it. The pattern is used in different teams through artsy. We've not migrated to 1p for teams, I'm interested in it though.

Using something like CP-Keys makes it easy for us to one day have a build server for app store builds that can have different keys, which the devs don't know about.

**Comment by jsleeuw** [comment]
So I guess the benefit you get from 1p is an added layer of security, yes? Is that what sets it apart from just sharing a text file between the developers on Dropbox?

**Comment by orta** [comment]
You [probably](http://www.theguardian.com/technology/2014/apr/11/dropbox-condoleezza-rice-privacy-surveillance) shouldn't be trusting dropbox with all your passwords and keys. They'd have to do a lot of work to pull them out of 1p without the key.

**Comment by jsleeuw** [comment]
OK, got it.
Thanks a lot for your help here, and for sharing cocoapods-keys with us!

**Comment by orta** [comment]
No problem :dancers: - have a nice day
