### ISSUE TITLE
Move Rx Nimble extensions into a new library

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eidolon#570]
They're reusable and should be put in their own pod, something like Nimble+Rx.

https://github.com/artsy/eidolon/blob/cb31168fa29dcc7815fd4a2e30e7c000bd1820ce/KioskTests/TestHelpers.swift#L108-L176

**Comment by orta** [comment]
can this be closed now Action exists?

**Comment by ashfurrow** [comment]
Well, Action is a specific extension relating to Rx production code, where this issue is related to functions that connect Rx and Nimble for unit testing. This won't take long to do, I'll try to get to it today.

**Comment by ashfurrow** [comment]
Created a repo here: https://github.com/ashfurrow/RxNimble/tree/master
