### ISSUE TITLE
ReachabilityManager's `reach` produces `true` when unreachable block executes.

### ISSUE THREAD

**Issue by azeff** [artsy/eidolon#572]
Hi, thanks for sharing the code! 

I was messing around and found something that I think is a bug. Take a look at this [line](https://github.com/artsy/eidolon/blob/master/Kiosk/App/GlobalFunctions.swift#L61). Shouldn't `unreachableBlock` produce an event with `false` value?

**Comment by ashfurrow** [comment]
Good catch! I think I mixed this up on https://github.com/artsy/eidolon/commit/3d7be3f69de67b975924fcdac9d4da96ec39bbd8 and we never caught it, thanks!

**Comment by ashfurrow** [comment]
This will be fixed once https://github.com/artsy/eidolon/pull/571 is merged. Thanks again!
