### ISSUE TITLE
You must specify a version in A.B.X format to deploy.? 

### ISSUE THREAD

**Issue by uthens** [artsy/eidolon#574]
Code sample:
https://github.com/artsy/eidolon/blob/master/fastlane/Fastfile

version = options[:version]
raise "You must specify a version in A.B.X format to deploy." if version.nil? || version.scan(/\d+\.\d+\.\d+/).length == 0

What is mean A.B.X format to deploy ? 

Error exception:
[17:07:30]: Driving the lane 'ios deploy_hockeyapp' 🚀
[17:07:30]: Variable Dump:
[17:07:30]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios deploy_hockeyapp"}
[17:07:30]: You must specify a version in A.B.X format to deploy.

**Comment by orta** [comment]
It means the version you specify must conform to [semantic versioning](http://semver.org) - so it must be `major.minor.patch` or you cannot deploy.

**Comment by orta** [comment]
+ Deploying is covered in the [deployment doc](https://github.com/artsy/eidolon/blob/master/docs/deployment.md)

> To make a deploy, run the following:

> `fastlane deploy version:A.B.C`

> The first time you deploy, you'll be asked to sign in to the developer portal through Fastlane. The password is in 1Password, too.

**Comment by uthens** [comment]
Thanks you so much, i will try testing and resolve today again :+1:

**Comment by xamaringeek** [comment]
When i input the version still have the problem, build error.
I used version 1.51.0, please see information on below:

Uthens-MacBook-Pro:ios uthen$ fastlane deploy_hockeyapp version:3.3.0
[10:08:55]: Using version: 3.3.0
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '86f6c6304f45b6169be19ba1919bad66'
The crash report has been stored locally '/tmp/sentry_86f6c6304f45b6169be19ba1919bad66.json'
Uthens-MacBook-Pro:ios uthen$ 

Information on temp file:
{
  "event_id": "86f6c6304f45b6169be19ba1919bad66",
  "message": "RuntimeError: \u001b[31mSyntax error in your Fastfile on line 242: Fastfile:242: syntax error, unexpected keyword_end, expecting end-of-input\u001b[0m",
  "timestamp": "2016-01-19T03:08:55",
  "time_spent": null,

More question: 
1) The version number 3.3.0 on fastlane should be the same version on x-code ? my version on x-code project is 3.3.0

2)  The version number will write on file : CHANGELOG.yml ? 
Sample on my .yml 
upcoming:
releases:
- version: 3.3.0
  date: January 15 2016
  notes:
  - Updates under the hood

Best, 
Uthen

**Comment by uthens** [comment]
When i input the version still have the problem, build error.
I used version 1.51.0, please see information on below:

Uthens-MacBook-Pro:ios uthen$ fastlane deploy_hockeyapp version:3.3.0
[10:08:55]: Using version: 3.3.0
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '86f6c6304f45b6169be19ba1919bad66'
The crash report has been stored locally '/tmp/sentry_86f6c6304f45b6169be19ba1919bad66.json'
Uthens-MacBook-Pro:ios uthen$

Information on temp file:
{
"event_id": "86f6c6304f45b6169be19ba1919bad66",
"message": "RuntimeError: \u001b[31mSyntax error in your Fastfile on line 242: Fastfile:242: syntax error, unexpected keyword_end, expecting end-of-input\u001b[0m",
"timestamp": "2016-01-19T03:08:55",
"time_spent": null,

More question: 
1) The version number 3.3.0 on fastlane should be the same version on x-code ? my version on x-code project is 3.3.0

2) The version number will write on file : CHANGELOG.yml ? 
Sample on my .yml 
----------------------------------------------------------------
upcoming:

releases:
- version: 3.3.0
  date: January 15 2016
  notes:
  - Updates under the hood
----------------------------------------------------------------

Best, 
Uthen

**Comment by uthens** [comment]
export HOCKEY_API_TOKEN='THE_SECRET_TOKEN_YOU_GOT_FROM_1PASSWORD'
export SLACK_URL='https://hooks.slack.com/services/REST_OF_THE_URL_FROM_1PASSWORD'

it's fixed!!! 

https://github.com/artsy/eidolon/blob/master/docs/deployment.md

**Comment by uthens** [comment]
I thinks this problem was fixed.

https://github.com/artsy/eidolon/blob/master/docs/deployment.md

export HOCKEY_API_TOKEN='THE_SECRET_TOKEN_YOU_GOT_FROM_1PASSWORD'
export SLACK_URL='https://hooks.slack.com/services/REST_OF_THE_URL_FROM_1PASSWORD'
