### ISSUE TITLE
bundle install don't work, how to fix on this problem ? 

### ISSUE THREAD

**Issue by uthens** [artsy/eidolon#576]
Sample: https://github.com/artsy/eidolon
----------------------------------------------------------------
git clone https://github.com/artsy/eidolon.git
cd eidolon
bundle install
bundle exec fastlane oss
----------------------------------------------------------------

>> Uthens-MacBook-Pro:eidolon uthen$ bundle install 
don't work how to resolve on this problem ? 

Last login: Mon Jan 18 22:56:11 on ttys004
Uthens-MacBook-Pro:eidolon uthen$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Fetching https://github.com/ffi/ffi.git
fatal: Could not parse object 'd94b923c1f574ff63743f0a3eefc917da03386b9'.
Git error: command `git reset --hard d94b923c1f574ff63743f0a3eefc917da03386b9` in directory
/Users/uthen/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/ffi-d94b923c1f57 has failed.
If this error persists you could try removing the cache directory
'/Users/uthen/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/cache/bundler/git/ffi-7fa1fad54f97b3471351dbde91d8b0a9444ce49e'
Uthens-MacBook-Pro:eidolon uthen$

**Comment by orta** [comment]
Did you try deleting `Users/uthen/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/cache/bundler/git/ffi-7fa1fad54f97b3471351dbde91d8b0a9444ce49e` like it asked, and re-runnning?

**Comment by ashfurrow** [comment]
We're seeing this on our [Continuous Integration](https://travis-ci.org/artsy/eidolon), too. Started over the weekend, still looking into it.

**Comment by ashfurrow** [comment]
Probably related to https://github.com/ffi/ffi/issues/461#issuecomment-172568651

**Comment by uthens** [comment]
Did you try deleting Users/uthen/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/cache/bundler/git/ffi-7fa1fad54f97b3471351dbde91d8b0a9444ce49e like it asked, and re-runnning? 

<<< I try to deleted on folder and re-rerunning, but still have the same problem..

Uthens-MacBook-Pro:eidolon uthen$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Fetching https://github.com/ffi/ffi.git
fatal: Could not parse object 'd94b923c1f574ff63743f0a3eefc917da03386b9'.
Git error: command `git reset --hard d94b923c1f574ff63743f0a3eefc917da03386b9` in directory /Users/uthen/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/ffi-d94b923c1f57 has failed.
If this error persists you could try removing the cache directory '/Users/uthen/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/cache/bundler/git/ffi-7fa1fad54f97b3471351dbde91d8b0a9444ce49e'
Uthens-MacBook-Pro:eidolon uthen$

**Comment by uthens** [comment]
now i can build this project, thanks you

**Comment by lihei12345** [comment]
@uthens could you tell me how did you fix this problem? thanks

**Comment by shingt** [comment]
Deleting this line worked for me:

https://github.com/artsy/eidolon/blob/24e36a69bbafb4ef6dbe4d98b575ceb4e1d8345f/Gemfile.lock#L3

Seemingly revision `d94b923c1f574ff63743f0a3eefc917da03386b9` does not exist and it causes this problem.

**Comment by tomaskraina** [comment]
This one helped me: https://semaphoreci.com/docs/fail-could-not-parse-object.html

**Comment by lihei12345** [comment]
@shingt this works for me. thanks

**Comment by ashfurrow** [comment]
Yeah, not sure what's up. ffi had problems with El Capitan, which is why we had that line. They seem to have resolved it, and maybe the commit hash is no longer accessible? Not sure. In any case, this solution worked for us, too: https://github.com/artsy/eidolon/commit/dec899a324e791de4774629c37b7bbe1310f313c

**Comment by ashfurrow** [comment]
So, thanks!

**Comment by cuongncFramgia** [comment]
You can try "sudo bundle install". It's work for me

**Comment by TorvaldsDB** [comment]
to re-run `bundle install` helps me out.

**Comment by limjinsun** [comment]
```
❯ rm -rf vendor/bundle/ruby/2.7.0/cache/*
```
remove your cache.
