### ISSUE TITLE
bundle installer : error >>> gem 'ffi', :git=> 'https://github.com/ffi/ffi.git', :branch => 'elcapt'

### ISSUE THREAD

**Issue by uthens** [artsy/eidolon#579]
I comment on the last line on Gemfile: eidolon project i can ignore gem ffi? 
and bundler install are worked.

========
Gemfile:
========
source 'https://rubygems.org'

gem 'cocoapods'

gem 'cocoapods-keys'

gem 'sbconstants'
gem 'second_curtain'
gem 'fastlane'
# gem 'ffi', :git=> 'https://github.com/ffi/ffi.git', :branch => 'elcapt'

=======
error information , when i bundler install and uncomment gem 'ffi'
=======
Uthens-MacBook-Pro:eidolon uthen$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Fetching https://github.com/ffi/ffi.git
fatal: Could not parse object 'd94b923c1f574ff63743f0a3eefc917da03386b9'.
Git error: command `git reset --hard d94b923c1f574ff63743f0a3eefc917da03386b9` in directory /Users/uthen/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/ffi-d94b923c1f57 has
failed.
If this error persists you could try removing the cache directory
'/Users/uthen/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/cache/bundler/git/ffi-7fa1fad54f97b3471351dbde91d8b0a9444ce49e'

**Comment by uthens** [comment]
Next problem on x-code i can't build project : 

diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

i try : sudo gem install cocoa pods and re-build again still same error on X-code.

**Comment by uthens** [comment]
Build on x-code to have the problem: on  ../eidolon/Kiosk/Supporting Files/PodsBridgingHeader.h

/Users/uthen/Projects/eidolon/Kiosk/Supporting Files/PodsBridgingHeader.h:1:9: 'Artsy_UIColors/UIColor+ArtsyColors.h' file not found

**Comment by uthens** [comment]
Now i open : Kiosk.xcworkspace workspace and rebuild ti's worked

http://stackoverflow.com/questions/31139534/pod-error-in-xcode-id-framework-not-found-pods

**Comment by ashfurrow** [comment]
👍
