### ISSUE TITLE
"please add the ensure_git_status_clean action to the beginning of your lane, or if you're absolutely sure of what you're doing then call this action with the :force option."  What is mean ? 

### ISSUE THREAD

**Issue by uthens** [artsy/eidolon#581]
[10:16:38]: This is a destructive and potentially dangerous action. To protect from data loss, please add the `ensure_git_status_clean` action to the beginning of your lane, or if you're absolutely sure of what you're doing then call this action with the :force option.

**Comment by uthens** [comment]
code same : 

desc "Release a new beta version on Hockey"
desc "This action does the following:"
desc ""
desc "- Verifies API keys are non-empty"
desc "- Ensures a clean git status"
desc "- Increment the build number"
desc "- Build and sign the app"
desc "- Upload the ipa file to hockey"
desc "- Post a message to slack containing the download link"
desc "- Commit and push the version bump"
lane :deploy do |options|

  version = options[:version]
  raise "You must specify a version in A.B.X format to deploy." if version.nil? || version.scan(/\d+\.\d+\.\d+/).length == 0

  hockey_api_token = ENV['xxxxxxxxx']
  raise "You must specify a HOCKEY_API_TOKEN environment variable to deploy." if hockey_api_token.nil?

  # Make sure not to ship with OSS
  verify_pod_keys

  # Make sure we start off with a clean slate
  ensure_git_status_clean          #<<<<<<<<<<<<<<< problem..

  # Increment build number to current date
  build_number = Time.new.strftime("%Y.%m.%d")
  increment_build_number build_number: build_number

.....

**Comment by uthens** [comment]
Other information: 
fastlane : v 1.53.0
ruby : v : ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin14.0]

**Comment by uthens** [comment]
ensure_git_status_clean  should be move to "before_all do section" is better ?

**Comment by orta** [comment]
it means make sure that `git status` returns nothing, so that you always have a blank slate when deploying.

**Comment by uthens** [comment]
Thanks you so much
