### ISSUE TITLE
Refreshing networking data sends the wrong data to existing cells

### ISSUE THREAD

**Issue by orta** [artsy/eidolon#591]
It's looking like we send the wrong starting/current bid data to the wrong cell during a sync of the sale artworks. It's easy to re-pro:

![2016-03-01 09_30_04](https://cloud.githubusercontent.com/assets/49038/13429849/31600c6a-df90-11e5-933f-726d043425cc.gif)

**Comment by orta** [comment]
I'm seeing View Model bindings being triggered for SaleARtworks that are not presented from the UI, perhaps they're not being disposed correctly?

![screen shot 2016-03-01 at 11 47 32 am](https://cloud.githubusercontent.com/assets/49038/13434319/68a8af66-dfa3-11e5-8cba-03c4ed4ddc08.png)

**Comment by ashfurrow** [comment]
Fun bug!
