### ISSUE TITLE
Question: This project got moved to RxSwift from ReactiveCocoa. Reason?

### ISSUE THREAD

**Issue by madnik** [artsy/eidolon#593]
This project got moved to RxSwift from ReactiveCocoa. I would be glad to know some kind of opinion about that from maintainers.

**Comment by orta** [comment]
Two blog posts cover this:
 
- http://artsy.github.io/blog/2015/12/08/reactive-cocoa-to-rxswift/
- http://artsy.github.io/blog/2015/09/18/Cocoa-Architecture-Dependencies/

:+1:
