### ISSUE TITLE
Kiosk crashing when logging in with passwords

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eidolon#597]

**Comment by alessandra-castillo** [comment]
To replicate crash: 

1. Enter next bidding increment.
2. Enter a phone number connected to existing Artsy account (Artsy account cannot be previously registered for the auction)
3. Prompted to enter email and password. 
4. Hit “Enter.”
5. App crashed.

App did not crash if I entered information from the “Use Artsy Login Details” prompt on this screen.
![img_0042](https://cloud.githubusercontent.com/assets/9465284/14573845/900d3f36-0325-11e6-913c-acfb9cf4b8fc.PNG)

**Comment by ashfurrow** [comment]
Confirmed, I've reproduced the crash locally. It's `EXC_BAD_INSTRUCTION` on `ConfirmYourBidArtsyLoginViewController.swift:63`. Investigating further...
