### ISSUE TITLE
Merchandizability Improvements

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eidolon#599]
Sat down with Alessandra and Melanie to discuss ideas to improve the Kiosk's merchanidazbility of artworks. 

- We need to think of the ramifications of the artwork page redesign that's happening across Artsy. @katarinabatina are there any fields we should be displaying if they're available?
- Editions aren't displayed (currently tracked on https://github.com/artsy/eidolon/issues/472 )
- "0 bids placed" gives a poor look for that lot, we should consider just not showing any string for lots without bids.
- "Lowest Bid" ordering uses only bids that have been placed, and not the starting bid. That's fine, but if many lots have no bids yet, then their _starting_ bids should define their ordering within the top of the list. So the list would be ordered [artworks without bids, ordered by starting bid][artworks with bids, ordered by those bid amounts].

**Comment by devangt** [comment]
In the 0 bids case lets say "Starting Bid = [value]" . Thats what P8 does.

**Comment by ashfurrow** [comment]
We're already displaying that, but we _also_ display the number of bids. This change would be to just not show that.
