### ISSUE TITLE
Contribute to eidolon

### ISSUE THREAD

**Issue by samirGuerdah** [artsy/eidolon#604]
Hello,

Can i contribute to this repository by submitting pull request or it's a "private" open source project ? Thanks for your answers.

**Comment by ashfurrow** [comment]
Hi there! This project is completely in the open, but we don't expect community contributions that add features or anything like that. If you have any questions or suggestions, we'd love to hear what have to say!

**Comment by orta** [comment]
I cover this quite a bit in http://artsy.github.io/blog/2016/01/13/OSS-Expectations/

👍 closing, only because we try to keep issues actionable - it's a good question
