### ISSUE TITLE
Fix "Bid Accepted" confirmation screen after auction closed

### ISSUE THREAD

**Issue by Nicole261** [artsy/eidolon#622]
I was helping a woman place a bid with 30 seconds left in the Silent auction. After typing in the new amount, bidder number, and pin number, the bid went through and said "Bid Accepted" popped up on the kiosk. The woman was standing next to me and saw this on the screen and was under the impression that she had won the lot. If this isn't a bug, it should say something along the lines of "Bid submitted" or "Bid Failed." This is the lot where this occurred: https://auctions.artsy.net/sales/ici-benefit-auction-2016/artworks/giacinto-occhionero-orange-drops/bidder_positions.

**Comment by ashfurrow** [comment]
Cool, going to close this issue to follow-up on this one: https://github.com/artsy/auctions/issues/220
