### ISSUE TITLE
ruby-2.1.1 is not installed on cd into eidolon dir

### ISSUE THREAD

**Issue by AndrewSB** [artsy/eidolon#628]
I was checking out your code to look at an implementation detail for Moya, and I noticed that when I `cd`'d into `eidolon`'s directory, my terminal prompted me to install the right version of ruby for your project.

```bash
➜  cd eidolon
ruby-2.1.1 is not installed.
To install do: 'rvm install ruby-2.1.1'
```

How did you guys swing that? Is it the `.ruby-version` file?

**Comment by ashfurrow** [comment]
That's correct! RVM is clever enough to check for it and automatically switch for you.

**Comment by AndrewSB** [comment]
that is really cool! Thanks @ashfurrow
