### ISSUE TITLE
Storyboard fonts need to be set in code

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eidolon#630]
It appears to be using the system font instead of our custom fonts:

![img_0052](https://cloud.githubusercontent.com/assets/498212/20726246/aee2bf8c-b642-11e6-8cb9-aca79a4c5442.PNG)

This bug is only present on the iOS 10 release.

**Comment by orta** [comment]
We used to see this in Folio I think so I'd always set the class as UILabel subclass that just sets the right font
