### ISSUE TITLE
MapTo function and parse of JSON

### ISSUE THREAD

**Issue by douglastaquary** [artsy/eidolon#635]
Hello @ashfurrow, Sorry for creating an issue for this subject. 
I'm making some examples based on some of the patterns you developed in the Artsy App. Thanks for sharing. But I came across a json parse problem using the `mapTo` function, and the `JSONAbleType` protocol. I would if possible a help, or any tips to go through this problem:

I have this json of response:
```json
{  
   "behaviors":[  
      {  
         "indicator":{  },
         "window":"DAILY",
         "format":"INTEGER",
         "value":6,
         "situation":"UNKNOWN"
      } ],
   "trays":[  
      {  
         "id":"0",
         "name":"favorites",
         "favorite":"true",
         "behaviors":[  
            {  
               "indicator":{  
                  "id":"1"
               },
               "window":"DAILY"
            } ],
   "dateRequest":"0"
}
```
and i have this model:

``` swift 
import Foundation
import SwiftyJSON

final class Dashboard: NSObject, JSONAbleType {
    
    dynamic var behaviors: [Behavior]?
    dynamic var trays: [Tray]?
    dynamic let dateRequest: String
    
    init(dateRequest: String, trays: [Tray]?, behaviors: [Behavior]?) {
        self.dateRequest = dateRequest
        self.behaviors = behaviors
        self.trays = trays
    }
    
    static func fromJSON(_ json: [String : Any]) -> Dashboard {
        let json = JSON(json)
        
         print("\n\(json)\n")

        let dateRequest = json["dateRequest"].stringValue
        
        let trays = (json["trays"].object as? [Tray])
        let behaviors = (json["behaviors"].object as? [Behavior])

        return Dashboard(dateRequest: dateRequest, trays: trays, behaviors: behaviors) 
    }
}
```
I tried to make arrays parser as well:

```swift
        if let behaviorsDictionary = json["behaviors"].object as? [String: AnyObject] {
            dashboard.behaviors = [Behavior.fromJSON(behaviorsDictionary)]
        }
```
but come `nil` too. :/

The only attribute that parses correctly  is `dateRequest`, but on arrays there is some data that end of process them come` nil`. 

This is my problem, it seems that there is no json structure and can not popular my model.

Can you help me, or can you give me some suggestions?

**Comment by ashfurrow** [comment]
Hey, don't worry about opening issues on this repo, that's why it's open source! 

It looks like you're using SwiftyJSON's `object` to access behaviors as a dictionary, but the JSON has an array. Would this work? 

```swift
if let behaviorsArray = json["behaviors"].object as? [[String: AnyObject]] {
    dashboard.behaviors = behaviorsArray.map { [Behavior.fromJSON($0)] }
}
```

I'm not entirely sure what's going on, but you've got the right approach to break down abstractions until things works. Keep it up and I'm sure you'll figure it out, and then you can build those abstractions back up. And hopefully right a blog post about what you've learned :wink:

**Comment by douglastaquary** [comment]
The example I showed did not work! But the one you showed worked! Thanks a lot for the help!🎉

**Comment by douglastaquary** [comment]
@ashfurrow, just one more question! :) The example you wrote worked perfectly for the `mapTo (object : Object.Self)` function. How would I modify the` mapTo (arrayOf : Object.Self)` function to put my parsed objects in this format that you gave me?

 ```swift
    fileprivate func listingAllBehaviors() -> Observable<[Behavior]> {
        
        let dashboardEndpoint = SenseAPI.dashboard(token: "iuytrweuytiuyt")
        
        let request = provider
            .request(dashboardEndpoint)
            .filterSuccessfulStatusCodes()
            .mapJSON()
            .mapTo(object: Dashboard.self)
        
        return request
            .map { dashboard in
                return dashboard.behaviors
            }
            
            .mapTo(arrayOf: Behavior.self)
            .logServerError(message: "\n --> \nNão fomos capazes de processar e analisar  os comportamentos\n -->")
            .catchErrorJustReturn([])
    }
```

 As it stands, it returns the error message of the function: `logServerError()`
```swift
            .mapTo(arrayOf: Behavior.self)
            .logServerError(message: "\n --> \nNão fomos capazes de processar e analisar  os comportamentos\n -->")
            .catchErrorJustReturn([])
```
How I could put my objects in this array using ```mapTo (arrayOf: Object.self)```
```swift
  func mapTo<B: JSONAbleType>(arrayOf classType: B.Type) -> Observable<[B]> {
        return self.map { json in
            guard let array = json as? [AnyObject] else {
                throw SenseError.couldNotParseJSON
            }
            
            guard let dicts = array as? [Dictionary] else {
                throw SenseError.couldNotParseJSON
            }
            
            return dicts.map { B.fromJSON($0)}
        }
    }
```

**Comment by douglastaquary** [comment]
@ashfurrow , I managed to do it another way, without using `mapTo(arrayOf: Object.Self)`. If you can explain how to do the `mapTo(arrayOf)` issue later, I'd be very grateful. 👍 Thank you very much!
