### ISSUE TITLE
App unable to connect to newer card readers

### ISSUE THREAD

**Issue by alessandra-castillo** [artsy/eidolon#658]
When in "Card Tester" mode with the newer card swipers, we only see: 

_Started searching
Reader is attached_

It does not reach _Reader is connected_ so we can't use the new swipers for capturing CC's right now.

**Comment by alessandra-castillo** [comment]
Hey @ashfurrow, did you hear back from Cardflight about this issue? It would be great to make use of the new swipers for our PP event on May 2, since 2 of our kiosks will be in LA at the same time. cc: @melanieborinstein

**Comment by ashfurrow** [comment]
I've not heard back from them, I'll poke them.
