### ISSUE TITLE
Remove Mixpanel integration (in favor of Segment)

### ISSUE THREAD

**Issue by wrgoldstein** [artsy/eidolon#663]
As part of an overarching effort to remove our dependency on (and stop paying for) Mixpanel, Eidelon should stop sending event data directly to Mixpanel via their client library.

This is part of https://github.com/artsy/minotaur/issues/105

**Comment by ashfurrow** [comment]
Looking into this, but there's some good news: we weren't currently tracking against Mixpanel anyway. I'll add Segment still.

**Comment by wrgoldstein** [comment]
Does that mean we can turn off our Mixpanel subscription without causing any problems here?

**Comment by ashfurrow** [comment]
Yup 👍
