### ISSUE TITLE
question about newTokenRequest

### ISSUE THREAD

**Issue by asasdasasd** [artsy/eidolon#680]
https://github.com/artsy/eidolon/blob/763861405b126d286241ddabb88b5e62eebe5ab5/Kiosk/App/Networking/Networking.swift#L53

if `self.provider.request(ArtsyAPI.xApp)`will be executed twice at the same time ?

**Comment by ashfurrow** [comment]
Yup, it's definitely possible. There are no negative consequences for requesting more than one token, old tokens stay valid when new ones are produced, so I didn't bother programming around it. Does that answer your question?

**Comment by asasdasasd** [comment]
👍
thanks a lot, you are a really good man with patience
