### ISSUE TITLE
Dimming buttons when popover / child controller is presented

### ISSUE THREAD

**Issue by richardtop** [artsy/eidolon#690]
Hi,
By iOS HIG any active elements should become dimmed once a popover or child controller is presented.

However, in the app, the elements are not dimmed. I wonder, whether this could be considered a bug, or the decision not to dim the elements was intentional.

![simulator screen shot - ipad air 2 - 2018-04-05 at 11 14 00](https://user-images.githubusercontent.com/8013017/38354672-131e2118-38c3-11e8-93a3-bace2c8bc2d2.png)

**Comment by orta** [comment]
Bug, we built those components from scratch, so they don't take the lack of focus into account

**Comment by orta** [comment]
I consider it a bug as it doesn't fit the HIG which we want to conform to, but I also don't consider it important enough to warrant doing - y'know?

**Comment by ashfurrow** [comment]
Totally!

**Comment by richardtop** [comment]
@orta, @ashfurrow actually, Apple HIG do not mention this issue at all. The only mention I found is in "iOS 7 UI Transition Guide":
_"When an alert or action sheet appears, iOS 7 automatically dimsthe tint color of the views behind it. To respond
to this color change, a custom view subclass that uses tintColor in its rendering should override
tintColorDidChange to refresh the rendering when appropriate."_

The reason why I asked in the first place, is that your app has a completely custom user interface, so it would be totally fine to use own design language to handle elements out of focus.

**Comment by orta** [comment]
Yeah, I still think your initial call was right. They are definitely in-actionable and while we state that entire thing is un-tappable via the darkness I think classing them as disabled also makes sense individually
